PythonError NameError
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'fail' isn't defined

